### ISSUE TITLE
What studies is the reviewer referring to?

### ISSUE THREAD

**Issue by vasishth** [vasishth/SchoknechtVasishthInterference#41]
The reviewer writes:

> numerous studies in the literature show that hierarchically intervening elements do generate strong syntactic interference

What studies does the reviewer refer to here? Can you name some examples? If these are the Julie Franck studies, then I think that what is meant by syntactic interference is something different. 

I don't want to start a discussion about this in the paper, just want to understand the reviewer's point.

**Comment by PSchoknecht** [comment]
Yes, I think the reviewer refered to the Julie Franck studies.
