### ISSUE TITLE
no acknowledgements section and no funding information

### ISSUE THREAD

**Issue by vasishth** [vasishth/SchoknechtVasishthInterference#44]
We have to acknowledge that the work was partly funded by the university of potsdam, and partly by the DFG:

This text has to be in the acknowledgements:

Partly funded by the Deutsche Forschungsgemeinschaft, Germany (DFG, German Research Foundation) — Project ID 317633480 (SFB1287), and the University of Potsdam, Germany.

**Comment by PSchoknecht** [comment]
\section*{Acknowledgements}
This research was funded by the Deutsche Forschungsgemeinschaft (DFG, German Research Foundation), Project ID 317633480, SFB 1287 and the University of Potsdam, Germany.
We thank Johanna Thieke, Romy Leue, Elise Oltrogge and Lisa Plagemann for assistance during data acquisition. We are grateful to Dario Paape for helpful discussions and three anonymous reviewers for thoughtful and constructive comments.
