### ISSUE TITLE
web-based SPR

### ISSUE THREAD

**Issue by PSchoknecht** [vasishth/SchoknechtVasishthInterference#45]
You wrote:
"Moreover, it is entirely possible that a stronger syntactic manipulation than
the one we used ends up showing a syntactic interference effect of the type that
Van Dyke (2007) originally reported. Indeed, our own findings would need to
be replicated, ideally by an independent research group, if we want to be sure
that in the present design there is no evidence for syntactic interference. **If
such a replication attempt is carried out, it would also be useful to conduct an
lab-based self-paced reading study to investigate our speculation earlier that
the absence of syntactic interference in our online SPR study may have been
due to participants adopting a good-enough processing strategy, leading to
only semantic interference being detectable.**"

I would prefer to drop the bold part. Firstly, good-enough processing could be adopted in the lab, too. Secondly, I think it wouldn't be wise at this point to draw attention towards the possibility that the web-based study might have poorer quality than lab-based studies. (There were no concerns regarding the study being web-based.)

**Comment by vasishth** [comment]
OK
