### ISSUE TITLE
confusing text in paper

### ISSUE THREAD

**Issue by vasishth** [vasishth/SchoknechtVasishthInterference#48]
> Because the distractor differed between conditions, we did not analyze distractor reading times.

> The reading times differences at the distractor and the pre-critical region are discussed below

These two sentences in the paper are contradictory.

**Comment by PSchoknecht** [comment]
Both statements are accurate. We did not run linear models on the distractor reading times, but we discuss their reading times, e.g., whether differences in plausibility or word length caused the reading times difference starting at the distractor.

**Comment by PSchoknecht** [comment]
If you have no further objections, I'm keeping the sentences as they are. I'm going to submit the paper soon.

**Comment by vasishth** [comment]
go ahead
